In [55]:
key = input('name of the data:')
lines = open(key+".csv", "r").read().splitlines()




import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(os.getcwd()+'/GOOG1718.csv')

SP =  pd.read_csv(os.getcwd()+'/^GSPC.csv')

SP = SP[['Date','Volume']]
SP.columns = ['Date','SP_Volume']



full = pd.concat([df.set_index('Date'),SP.set_index('Date')],axis=1, join='inner').reset_index()

full['Volume_ratio'] = full.Volume/full.SP_Volume

full['Vol'] = full.Close.rolling(7).std().bfill()



tostandard = np.array([full['Volume_ratio'],full['Vol']]).T



full[['Volume_ratio','Vol']] = StandardScaler().fit_transform(tostandard)

full.to_csv('fulldata.csv',index=False)

In [154]:
res = [1,2,3,4,5]

In [174]:
res = np.array([res])


In [175]:
res.shape

(1, 5)

In [138]:
np.array([res,res]).shape

(2, 5)

In [151]:
otherdata = np.array([full.Volume_ratio.values,full.Vol.values])[:,0:5]

In [172]:
otherdata.shape

(2, 5)

In [177]:
np.concatenate([res,otherdata]).shape

(3, 5)

In [181]:
t = 1
c + otherdata[:,0:1]

array([[-1.39852527, -1.1465252 ],
       [-1.66147519, -1.92442511]])

In [187]:
10*otherdata[:,0:1]

array([[-6.99262633],
       [-9.62212553]])

In [182]:
otherdata[:,0:1]

array([[-0.69926263],
       [-0.96221255]])

In [189]:
res = [1,2,3,4,5]

In [194]:
3*[res[0]]+res[0:1]

[1, 1, 1, 1]

In [193]:
type(res[0:1])

list

In [228]:
otherdata

array([[-0.69926263, -0.18431264,  0.25356139, -0.7488343 , -0.21794142],
       [-0.96221255, -0.96221255, -0.96221255, -0.96221255, -0.96221255]])

In [229]:
np.concatenate([np.array([res]),otherdata])

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [-0.69926263, -0.18431264,  0.25356139, -0.7488343 , -0.21794142],
       [-0.96221255, -0.96221255, -0.96221255, -0.96221255, -0.96221255]])

In [216]:
otherdata

array([[-0.69926263, -0.18431264,  0.25356139, -0.7488343 , -0.21794142],
       [-0.96221255, -0.96221255, -0.96221255, -0.96221255, -0.96221255]])

In [271]:
d = -10

In [272]:
otherdata.shape

(2, 5)

In [273]:
np.repeat(np.array([otherdata[:,0]]),-d, axis=0).T.shape

(2, 10)

In [274]:
otherdata[:,0:3].shape

(2, 3)

In [277]:
all_data = np.concatenate((np.repeat(np.array([otherdata[:,0]]),-d, axis=0).T, otherdata[:,0:1]), 1)

In [278]:
all_data.shape

(2, 11)

In [239]:
np.repeat([otherdata[0]],d, axis=0)

np.append(np.repeat(np.array([otherdata[:,0]]),d, axis=0),otherdata)

ValueError: negative dimensions are not allowed

In [203]:
otherdata[0]

array([-0.69926263, -0.18431264,  0.25356139, -0.7488343 , -0.21794142])

In [280]:
d = -10
t = 0
data = [1,2,3,4,5,6,7]
a = -d * [data[0]] + data[0:t + 1]

In [281]:
data[0:t + 1]

[1]

In [282]:
len(a)

11

In [285]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
